### ISSUE TITLE
Run monitoring services on system start

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#101]
Some features of BR would be on as the system starts. These would obviously be the ones which do not consume the resources intensively. Monitoring falls under this.

Resource: [link](https://timleland.com/how-to-run-a-linux-program-on-startup/)

**Comment by Pratik32** [comment]
I will have a look at this.I guess we have to write init script for older linux versions that do not support systemd.

**Comment by pavansai1** [comment]
I would like to pick up this as a part of GSScC'20

**Comment by Harkishen-Singh** [comment]
I dont think this is necessary. Also, @Pratik32 has implemented this in a way. So if required in future, we can modify the changes done by him.
