### ISSUE TITLE
Extend support for Querier

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#107]
The Bench-routes-querier supports only one operation- `FetchAllSeries()` _(returns all the time-series values for a particular route till date)_.

We need to implement other simpler querying operations:
1. Starting time given, end at the most recent data-value
2. Ending time given, starting at the legacy data-value
3. Starting time given, ending time given

**Comment by aquibbaig** [comment]
@Harkishen-Singh Let's think of it as a form which queries such as "Last week results". In that case, we need **time.now() vs query time** isolation of the graph. Ain't it? So, we need to put **switch** statements based on exact query matches

**Comment by ganeshpatro321** [comment]
Are we planning to do this in the client-side, after getting all the series to the client, or will we support the dumped data too? @Harkishen-Singh

**Comment by Harkishen-Singh** [comment]
@ganeshpatro321 No, this has to be from the server-side since if we implement in the client end, then a lot of data (in MBs, possibly in GB for legacy data) needs to be sent over the air. hence, we plan to sent only the queried data only.

**Comment by Harkishen-Singh** [comment]
> @Harkishen-Singh Let's think of it as a form which queries such as "Last week results". In that case, we need **time.now() vs query time** isolation of the graph. Ain't it? So, we need to put **switch** statements based on exact query matches

yes, we can use such as well. mostly, we can provide such options as dropdown and then send the request to the service by converting into the time quantum (time nano secs from 1970) according to the latest **tsdb** design.

**Comment by ganeshpatro321** [comment]
Yeah, sure thing. @Harkishen-Singh That was a lame question to ask.

**Comment by pavansai1** [comment]
I would like to pick up this as a part of GSScC'20

**Comment by Harkishen-Singh** [comment]
This is done in #230. Closing it.
