### ISSUE TITLE
Consider unnecessary logging to secondary storage and not terminal

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#116]
**Describe the bug**
Presently, all events are being logged into the terminal. This leads to spamming and hence the useful log gets past. We need to categorise those events which need log ( like while a start, and in course of any error or exception in runtime) and show them only in the terminal. The rest (the one currently being done) can be directly written into the log without being shown in the terminal.

**Comment by ganeshpatro321** [comment]
#134
