### ISSUE TITLE
pre-commit for initial tests

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#117]
A lot of CI tests fail due to lack of proper formatting. Hence, we need `fmt` check (note: only check) and if not found in format, then throw an exception, thereby preventing commit.

Other suggestions in pre-commit are most welcome.

Useful resource: [link](https://github.com/zairza-cetb/bench-routes-electron/pull/22/files)

**Comment by Jayashree-panda** [comment]
@Harkishen-Singh I will like to work on this issue.
