### ISSUE TITLE
New brlogger for supporting independent log writes to secondary storage

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#118]
The current logger writes into the terminal (even trivial data which is useless for the terminal thereby spamming the terminal, but for tracing, would be important and hence flushing in the secondary storage) and the log file as well. We need a new logger which can write specific data to the log _(secondary storage)_  and some specific data to terminal and others to both terminal and secondary storage.

Further on later stages, this will implement the compression scheme to compress logs.

**Comment by ganeshpatro321** [comment]
#134
