### ISSUE TITLE
support for request-response delay

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#12]
OS: universal

#### Describe
For each route, the delay or increase on the req-res time would lead to more likeliness of a request being a timeout and hence a bad performance functionally and non-functionally as well. This module should be capable to track the variation of req-res time, and other necessary details which seem necessary.

**Comment by ankitjena** [comment]
We would need the type of the request to mock it. Discussion remains on how to take the routes from user. Plus for `POST` or `PUT` we would need to send some data for the request to work.

I think we can ask user to create mock routes for using bench-routes application where the request-response cycle works on a dummy database. But TBH this is too much work for someone.

**Comment by aquibbaig** [comment]
@ankitjena Focus on `GET` for now
