### ISSUE TITLE
Reduce redundancy in .tsx files

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#126]
We have good amount of redundancy in react UI. Redundancy includes react-chartjs code, `public opts` function etc which are found in `Ping.tsx`, `Jitter.tsx`, `FloodPing.tsx`, `Res-res.tsx`.

Other modular improvements are most welcome.

**Comment by Jayashree-panda** [comment]
@Harkishen-Singh I would like to take this issue.

**Comment by prajwal714** [comment]
Has the issue been resolved? if not I would like to take this issue.

**Comment by Harkishen-Singh** [comment]
@prajwal714 yeah it is open. You can go ahead with its implementation.

**Comment by vidyasonawane** [comment]
Is the issue fixed? If not, I would like to work on it.
