### ISSUE TITLE
Module headers.

### ISSUE THREAD

**Issue by ganeshpatro321** [zairza-cetb/bench-routes#136]
A header beside bench-route, describing which component/page we are in would be better for user, not to get confused.

![Screenshot from 2020-01-04 10-57-44](https://user-images.githubusercontent.com/30416891/71760274-1d298100-2ee1-11ea-9c1e-2420afde5e69.png)

**Comment by gunjanmimo** [comment]
SIr, I wan to work on this issue?

**Comment by akshaysingh5** [comment]
I would like to work on this issue, kindly assign me.
