### ISSUE TITLE
Flood Ping module page UI bug.

### ISSUE THREAD

**Issue by ganeshpatro321** [zairza-cetb/bench-routes#137]
**Describe the bug**
Flood ping module page contains two charts, these charts overflow the screen width, but these aren't scrollable. Mostly some css fix would be needed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'benchmarks/flood-ping'
2. Select an URL and click 'show'
3. When the app is in full-screen, you cannot see the second chart.
4. When you resize the app-screen size to a smaller size, you can see the second chart coming up.

**Expected behaviour**
The page should be scrollable and both the charts should be visible.

**Screenshots**
![Screenshot from 2020-01-04 11-10-35](https://user-images.githubusercontent.com/30416891/71760390-da68a880-2ee2-11ea-8ba1-198232a89aba.png)
![Screenshot from 2020-01-04 11-10-30](https://user-images.githubusercontent.com/30416891/71760391-dd639900-2ee2-11ea-8c19-c7ccf01f8b83.png)

**Comment by Harkishen-Singh** [comment]
This is fixed with the merge of https://github.com/zairza-cetb/bench-routes/pull/141.
Closing this.
