### ISSUE TITLE
Handle case when data received is null.

### ISSUE THREAD

**Issue by ganeshpatro321** [zairza-cetb/bench-routes#139]
**Describe the bug**
When we query for time series data from the bench-routes server, there maybe certain cases when there is no data, and the data returned to the client is null. The current react code doesn't handle this case, and the app crashes with unhandled rejection giving (TypeError): data is not iterable. (as it null).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'benchmarks/ping'
2. Select on 'https://www.bing.com/'
3. Click Show

There are no data for bing.com, so data returned is null.

**Expected behaviour**
A clear way informing the user that there is no data for the same.

Similar kinds of conditions should be handled for all the modules.

**Screenshots**
![Screenshot from 2020-01-05 17-57-29](https://user-images.githubusercontent.com/30416891/71780133-d4f38700-2fe4-11ea-8695-96ee2d3324ea.png)

**Comment by akshaysingh5** [comment]
I would like to work on this issue, please give me a starting point.

**Comment by Harkishen-Singh** [comment]
can someone confirm if this still exists?
