### ISSUE TITLE
url in ping command throws exception when input except domain or IP

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#14]
**Describe the bug**
We expect ping command to return the time interval between a pure request and response. However, when the url is **19.343.235.12:9000** or **google.co.in/search?q=...** then the ping throws `Name or service not known`.

However, **19.343.235.12** or **google.co.in** will work as expected. This leads to the conclusion that ping command acts on pure IP address as the domain name themselves corresponds to the IP address *( which are mentioned in the DNS settings )*.

We need to add a check or filter to prevent the further flow or to filter the url to the acceptable standards.
**To Reproduce**
Steps to reproduce the behaviour:
1. Open terminal
2. type `ping -c 10 www.google.com/search?q=hi` or `ping -c 10 35.196.226.253:9000`
3. Note the `Name or service not known`

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: fedora
 - Version: 85be4f100f8560b49480e8e259cbac34d7acf3a3

**Comment by ankitjena** [comment]
Does this mean that we cannot use `ping` for any other route than the domain name?

**Comment by Harkishen-Singh** [comment]
@ankitjena .That isn't what I meant. Ping does its process well as we expect an require. The thing is that we need filters so that we could avoid the exceptions which might arise if the user passes a faulty IP or Domain.

Ping tests can only be done on VM IP which is what is happening since it aims to find the idle time a VM takes to respond to the traffic and not the time taken by the route. The route part would be covered under **req-res delay**

**Comment by binayakbehera999** [comment]
@Harkishen-Singh . Does that mean that we have to create filters to filter out the pure IP address or the domain name for the URL supplied?

**Comment by Harkishen-Singh** [comment]
@binayakbehera999  No. What I mean to say is ping command works on the pure domain or IP address. 

 I feel, removing routes and other unrelated stuff from the base URL is easier than to dig domain name out from the same.

**Comment by Harkishen-Singh** [comment]
@ganeshpatro321 we currently have a temporary solution by hard coding url end points which was submitted by jayashree. We still have to find a permanent solution of filtering the URL for ping test.
