### ISSUE TITLE
Consistent frontend design

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/bench-routes#150]
**Is your feature request related to a problem? Please describe.**
A consistent frontend design, major refactor of UI components making them easy to grasp and 
contribute as the code now is a bit messy.

**Describe the solution you'd like**
We would like to use `antd's` dashboard solution for enterprises, that comes with a predifined layout.

**Additional context**
Any one of these layouts will be perfect. "https://ant.design/components/layout/"

**Comment by aquibbaig** [comment]
@Harkishen-Singh Should we go for ant-design or [Patternfly](https://www.patternfly.org/v4/)

**Comment by Harkishen-Singh** [comment]
@aquibbaig, we are already using `reactstrap` which uses bootstrap components. That makes the ui fairly light. So, we should keep things close to this. yeah, we can go with ant or patternfly but things should be in material fashion and where ever applicable, use the `reactstrap` first since it is simple bootstrap.

**Comment by aquibbaig** [comment]
@Harkishen-Singh Patternfly is no doubt good but lacks community(hence buggy). Ant-design is way more stable.

**Comment by vattytrivedi** [comment]
@Harkishen-Singh Mixing two components aren't a great idea if required will replicate from either libraries

**Comment by Harkishen-Singh** [comment]
@vattytrivedi sure. That would be best to reduce redundancy. For now, let's stick to reactstrap as it is simple and based on bootstrap, so would be easier for the contributors. Is that okay? @aquibbaig

**Comment by aquibbaig** [comment]
@Harkishen-Singh Reacrstrap +1

**Comment by Harkishen-Singh** [comment]
The current v1.1 looks great to the eyes along with the consistency. Hence, closing. If any views, feel free to open again.
