### ISSUE TITLE
Do not display charts when no data is returned from a url

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/bench-routes#160]
**Is your feature request related to a problem? Please describe.**
See #139.
**Describe the solution you'd like**
#139 has a fix #159, but we wouldn't want to display empty charts when there is no data. So there will be an extension on top of #159.

**Comment by Harkishen-Singh** [comment]
We would need something like a component saying something similar to `Graph not found` instead of the chart component.

**Comment by prajwal714** [comment]
I am interested in this issue for GSSOC '20

**Comment by Harkishen-Singh** [comment]
@aquibbaig why is this marked as `not-ready`?

**Comment by ShrutiAggarwal99** [comment]
Would like to work upon this issue

**Comment by Harkishen-Singh** [comment]
sure @ShrutiAggarwal99. please go ahead with the fix.

**Comment by aquibbaig** [comment]
@Harkishen-Singh Can be implemented in `v1.0`. @ShrutiAggarwal99 TIP: Have a look at https://reactjs.org/docs/code-splitting.html. Hope this helps!

**Comment by ShrutiAggarwal99** [comment]
Thanks @aquibbaig I'll check it out
