### ISSUE TITLE
Use dynamic loading for charts

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/bench-routes#161]
**Is your feature request related to a problem? Please describe.**
If there is some form of delay in render of a component, it is better to load a spinner instead and show the component only after it has been loaded. Code splitting is done when codebases get really large and help us not load entire components at a time.

**Describe the solution you'd like**
We can use dynamic imports to load components in our application.

**Resources**
[Code Splitting](https://reactjs.org/docs/code-splitting.html#reactlazy).
[Usage in tsx](https://stackoverflow.com/questions/54150819/using-react-lazy-with-typescript).

**Comment by Harkishen-Singh** [comment]
@aquibbaig, this is good from UX point. But I was thinking since we already support real-time streaming of data _(and hence sockets)_, we can make graphs being refreshed in regular intervals which happens from a push in service _(Note: only from service)_. This derives the true sense of dynamic graphs.

**Comment by vipuldcoder** [comment]
I am Interested with the issue.

**Comment by Harkishen-Singh** [comment]
@vipuldcoder sure, you can go ahead with this.

**Comment by aquibbaig** [comment]
@vipuldcoder I think this issue needs to wait for now, because we are on our way to make a new version of our dashboard in #167, you might want to contribute to that instead. Thanks for your interest in bench-routes.

**Comment by Harkishen-Singh** [comment]
Unrelated now.
