### ISSUE TITLE
Fix issues related to security and performance

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#164]
Current status in deepsource:
- [ ] 3 security issues
- [ ] 1 performance issue
- [ ] 1 style issue

https://deepsource.io/gh/zairza-cetb/bench-routes/run/41bf49cb-36f2-4c0a-8d72-0d6c3fc5b750/go/

**Comment by maheshschand** [comment]
Interested. Could you please assign to me?

**Comment by muskankhedia** [comment]
@maheshschand Sure. Go ahead.

**Comment by Harkishen-Singh** [comment]
@maheshschand any updates?

**Comment by maheshschand** [comment]
Sorry I can't resolve it. Can you unassign me?

**Comment by Harkishen-Singh** [comment]
Ahh, sadly, these are no more available. Closing for now. Consider reopening if any related issues are reported.
