### ISSUE TITLE
Migrate user interface to material-ui

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/bench-routes#167]
**Is your feature request related to a problem? Please describe.**
For people who are picking up issues, getting started with ui seems pretty hard for a js newbie cause the workflow is pretty confusing as in now. 

**Describe the solution you'd like**
We would restructure the code structure to have a proper data flow and migrate to best possible ui standards such as material-ui.

**Describe alternatives you've considered**
We have used reactstrap which doesn't serve the purpose of an easy code structure as it has no good layout components such as Grids, Boxes, etc.

**Comment by aquibbaig** [comment]
Things to be done:
- [ ] Remove reactstrap completely
- [ ] setup material-ui
- [ ] Refactor Layout components
- [ ] Refactor service-ui page components
- [ ] Refactor other components
- [ ] Write tests and close

**Comment by divyaprakash-Rx** [comment]
I want to work on it.
Please assign it to me

**Comment by aquibbaig** [comment]
@divyaprakash-Rx Awesome! Thanks for your interest. I'd like you to wait for #174 first. That would strike out Tasks "1, 2, 3" from https://github.com/zairza-cetb/bench-routes/issues/167#issuecomment-594346139. After that we can carry on with the migration. Which is building service-ui pages. You wanna pick that up? If yes, I'd open up a new subissue and track it along this. We have to build individual pages for the modules we have. Care to look at #175?

**Comment by divyaprakash-Rx** [comment]
Ok

**Comment by Harkishen-Singh** [comment]
lot of issues are related to this. We should refer those issues here as links and close them, so as to keeps the issues, features and bugs focused.

**Comment by Harkishen-Singh** [comment]
Mostly covered up. Hence closing this.
