### ISSUE TITLE
Update the readme with the postman documentation link

### ISSUE THREAD

**Issue by muskankhedia** [zairza-cetb/bench-routes#169]
#### Describe
This is the link to the postman documentation for Bench-routes: [Postman link.](https://documenter.getpostman.com/view/6521254/SzRuWqq9)

Add the link to the readme.md with some explanation.

**Comment by maheshschand** [comment]
Interested. Could you please assign this to me @muskankhedia ?

**Comment by maheshschand** [comment]
Interested. Could you please assign this to me @muskankhedia ?

**Comment by muskankhedia** [comment]
@maheshschand Sure.

**Comment by maheshschand** [comment]
@muskankhedia I updated README.md with postman documentation. Could you please review it?

**Comment by Chetanjain10** [comment]
Could you please assign me this task. This is going to be my first task. please assign it to me.

**Comment by muskankhedia** [comment]
@Chetanjain10 This issue has already been solved by @maheshschand earlier. Please look over the other issues and feel free to take up and ask doubts.
