### ISSUE TITLE
Link the start and stop button with the service in monitoring field

### ISSUE THREAD

**Issue by muskankhedia** [zairza-cetb/bench-routes#170]
**Describe the bug**
Currently, the start and stop button in the monitoring screen is not working. It should be linked with the service and start and stop the monitoring of routes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the server
2. Run the dashboard UI
3. Click on the `monitoring` option
4. Click on the start or stop button 
5. Buttons won't work

**Expected behaviour**
On clicking the start button the monitoring of routes should start and the value for `req-res-delay-or-monitoring` should change from passive to active and vice versa for the stop button

**Screenshots**
![Screenshot from 2020-03-04 14-50-44](https://user-images.githubusercontent.com/36980003/75865359-718da600-5e29-11ea-9c0e-11df3aeb0891.png)

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Version [e.g. commit sha / release version]: v1.0-alpha.1

**Comment by divyaprakash-Rx** [comment]
I want to work on this issue. Please assign it to me.

**Comment by muskankhedia** [comment]
Sure. Go ahead.

**Comment by divyaprakash-Rx** [comment]
@muskankhedia Ok

**Comment by shwhite17** [comment]
wanna work on it?

**Comment by muskankhedia** [comment]
@shwhite17 Sure. You can solve the issue and make a PR for the same.

**Comment by ShrutiAggarwal99** [comment]
I would like to work on this issue too

**Comment by ShrutiAggarwal99** [comment]
@shwhite17 Are you working on this issue? If not I'd like to take it up.
