### ISSUE TITLE
Convert the approach.md to proper markdown file

### ISSUE THREAD

**Issue by vattytrivedi** [zairza-cetb/bench-routes#171]
#### Describe
Update the file with the proper format of markdown
[Approach file link](https://github.com/zairza-cetb/bench-routes/blob/master/approach.md)

**Comment by Harkishen-Singh** [comment]
This is open for contributions for gssoc participants. Assignee is for reviews.

**Comment by muskankhedia** [comment]
@vattytrivedi Please provide the label with only one difficulty level as mentioned in the gssoc guidelines. So, I am removing one of label *beginner* from the issue.

**Comment by maheshschand** [comment]
Interested. Could you please assign this to me?

**Comment by akshaysingh5** [comment]
I would like to work on this issue, please elaborate.

**Comment by Harkishen-Singh** [comment]
I think this is already done. Closing it so that others don't confuse. Thanks.
