### ISSUE TITLE
Implement Ping module in v1.1 dashboard

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/bench-routes#175]
**Is your feature request related to a problem? Please describe.**
We moved to material-ui. We need to implement our modules as per material-ui components.

**Describe the solution you'd like**
Every page extends to BaseLayout. Use material-ui components to design the page.

**Comment by aquibbaig** [comment]
First, #174 needs to be merged.

**Comment by akshaysingh5** [comment]
I would to like work on this issue but I don't know up to what extent the UI needs to be changed. Please elaborate.

**Comment by Harkishen-Singh** [comment]
This is done. Closing.
