### ISSUE TITLE
Shift to yarn for frontend support

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#176]
I think its time, we should shift to yarn. Yarn provides better package management and security benefits.

**Comment by maheshschand** [comment]
Interested. Could you please assign it to me @Harkishen-Singh ?

**Comment by Harkishen-Singh** [comment]
sure @maheshschand . In this, I think we would require some installation instructions which should be done in `INSTALL.md`, and a `yarn.lock` should be enough. Will that be okay, @aquibbaig @ganeshpatro321 ?

**Comment by maheshschand** [comment]
Please review this. I added yarn.lock file.

**Comment by maheshschand** [comment]
Please review this @Harkishen-Singh . I added yarn.lock file.

**Comment by aquibbaig** [comment]
@maheshschand Hello. Great work! I have added a couple of comments for you.

**Comment by maheshschand** [comment]
I made a pull request #177 . Could you please review it? @aquibbaig

**Comment by maheshschand** [comment]
Again. Could you please add a label that would help in gssoc scoring?

**Comment by maheshschand** [comment]
@ganeshpatro321 I made a pull request #180 Please review this.
