### ISSUE TITLE
Speeding up Travis CI Build

### ISSUE THREAD

**Issue by maheshschand** [zairza-cetb/bench-routes#178]
**Problem**
Travis CI Build is slow for the project.

**Solution**
We can speed the build by using "parallelizing" concept.

**Comment by maheshschand** [comment]
I like to work on it through GSSOC. Could you please assign me this @Harkishen-Singh ?

**Comment by maheshschand** [comment]
@Harkishen-Singh Could you please look into this issue? Is this feature required or not?

**Comment by ganeshpatro321** [comment]
@maheshschand This would be a great feature. Please provide some useful resources here.

**Comment by maheshschand** [comment]
@ganeshpatro321 I read from this documentation. [Speeding up the build](https://docs.travis-ci.com/user/speeding-up-the-build/)
