### ISSUE TITLE
Make collector available as independent tool along with the current implementation in main.go

### ISSUE THREAD

**Issue by ganeshpatro321** [zairza-cetb/bench-routes#189]
The current design of collector acts as an independent application, with a separate `main.go` file. And the current implementation also has duplicate code, doing the same functionality. 
 - if enableProcessCollection block in src/main.go and  src/collector/main.go 

What I suggest is maintaining collector similar to other modules(same design). This will also help integrating collector with the UI.

Tasks:
 - [ ] Redesign Collector (requires discussion)
 - [ ] Stop functionality 
 - [ ] UI Integration

@Harkishen-Singh  @aquibbaig @ankitjena

**Comment by Harkishen-Singh** [comment]
Yes, now this can be done for:
1. process-collector
2. system-collector
