### ISSUE TITLE
Add newer tests to the tsdb module for validating chain propagation

### ISSUE THREAD

**Issue by muskankhedia** [zairza-cetb/bench-routes#22]
### Describe

As the database is managed by the tsdb, the data is being stored in the JSON file in the form of an array of objects. The JSON file contains a chain of blocks and various operations are implemented on the data like `append, pop, Positional Block` etc. So during the use of the data, we need to validate if the data stored is correct or have been corrupted in the way while performing different functions.

There are various ways. As one of them is that the data can be tested by chain propagation i.e. propagating through every block of the element and making a check does the address of the Next Block exists or not. And finally having a check on the length of the element with the loop size for the final confirmation.

**Other suggestions are most welcome.**

**Comment by Harkishen-Singh** [comment]
@Jayashree-panda  please have a look

**Comment by binayakbehera999** [comment]
@Harkishen-Singh I would like to work on this.

**Comment by Harkishen-Singh** [comment]
@binayakbehera999  sure. pls go-ahead
