### ISSUE TITLE
Go profiling in bench-routes

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#226]
We need to support profiling of go. This is necessary to get an insight into the mechanism happening in the go-routines and in the heap.

**Comment by akshaysingh5** [comment]
Can you please elaborate on the issue and give some initial guidance, I would like to work on this issue.,

**Comment by Harkishen-Singh** [comment]
Sure @akshaysingh5 . The best place would be the original docs which are rather simple to understand, https://golang.org/pkg/net/http/pprof/ and along with articles on the web that you can search for in-depth knowledge.

**Comment by aquibbaig** [comment]
@akshaysingh5 Are you working on this issue?

**Comment by Harkishen-Singh** [comment]
@akshaysingh5 any updates?

**Comment by aquibbaig** [comment]
I guess there are no updates on this. @akshaysingh5 Feel free to take up any other issues.

**Comment by aquibbaig** [comment]
Solved via #252
