### ISSUE TITLE
store user-details as a part of the configuration file

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#25]
The database used as of now is tsdb, which is helpful for storing values as a time-series. However, we need to store general details which would be loaded each time on startup. This includes _avg response length, count of time-series,_ and other relevant things.

**Comment by aquibbaig** [comment]
#24 depends on this, I'm assigning myself for now. Others are welcome to!

**Comment by Harkishen-Singh** [comment]
@aquibbaig  sure!

**Comment by aquibbaig** [comment]
Fixed via #34
