### ISSUE TITLE
Improve filtering of urls into domain names for the ping cmd

### ISSUE THREAD

**Issue by C-Anirudh** [zairza-cetb/bench-routes#32]
**OS**: All

#### Describe
The `HTTPPingFilter` method found at `/src/lib/filters/` falls short in certain places.
- [ ] Doesn't return an error if the url cannot be filtered to a syntactically correct domain name. (i.e., the method returns some domain string for the invalid urls `https://www.google` , `https://www.com`, etc ). **Possible solution**: Use regex to check whether the filtered domain name is valid.

- [ ] **This may be a rare event** but ping may resolve to an ip even for an invalid albeit syntactically correct domain name. Read: https://superuser.com/questions/836997/why-is-ping-resolving-to-an-ip-198-105-254-228-for-any-random-hostname-that-i-ty/836999#836999. I don't know whether we can do anything about this, but we can warn the user about such a possibility.

**Comment by C-Anirudh** [comment]
@Harkishen-Singh I would like to take this up.

**Comment by Harkishen-Singh** [comment]
@C-Anirudh pls go head
