### ISSUE TITLE
Reduce redundancy in tsdb for different modules

### ISSUE THREAD

**Issue by ankitjena** [zairza-cetb/bench-routes#36]
Desktop (please complete the following information):

OS: ubuntu

#### Describe
Currently after end-to-end integration of the ping module, almost all the methods and structures are written again with minor changes, like `Block` and `BlockPing`. When we will add more modules there will be lot of redudancy. For example, `Block`, `BlockFloodPing`, `BlockJitter`, `BlockReqRes` etc. There must be a better way to do this.

**Comment by ganeshpatro321** [comment]
@Harkishen-Singh one more thing!

There are certain functions such as "append" which does the same thing for all the modules. Is it required to create different functions for different modules?

**Comment by Harkishen-Singh** [comment]
@ganeshpatro321  @ankitjena, for normal cases (except ping and flood ping), we require the results to be stored in tsdb. But, the default design of tsdb supports storing a single value corresponding to the time scale. But in the case of ping, we were required to store 4 different values corresponding to a single timestamp - min, mean, max, mdev. That's y we went for different functions like `BlockPing`.

but, as far as other modules are concerned, I don't see any multiple values needed to be stored corresponding to a single timestamp. So, the default design would work.

**Comment by Harkishen-Singh** [comment]
@ankitjena  we can come with an approach that could be universal for each module and thus reducing the redundancy. That would be really great.

**Comment by ankitjena** [comment]
@Harkishen-Singh that's what I was suggesting

**Comment by ankitjena** [comment]
@Harkishen-Singh What would be the better approach, any suggestions?

**Comment by Harkishen-Singh** [comment]
@ankitjena  nothing as of now. If something strikes will share here.

**Comment by Harkishen-Singh** [comment]
@ankitjena one way we can do this is by storing the complex values as string in `datapoint` _(of type `string`)_ field. This way, we can store the value by marshalling it and retrieve it in the same process and store in the respective lower level structure.

**Comment by aquibbaig** [comment]
Let's have a common `blockType` struct with a common timestamp and a datapoint,
The datapoint can be of various types since it is different for different modules as per basic Object Modelling

**Comment by ganeshpatro321** [comment]
Can embedded struct types help here? Or the same thing?
