### ISSUE TITLE
Initial checking of configuration rules

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#40]
We have no checks for verifying the configuration file `local-config.yml`. This should be done just before loading the config file into the bench-routes environment.  In case of mismatch, an error should be thrown, thus terminating the system.

**Comment by JayjeetAtGithub** [comment]
Hi @Harkishen-Singh. I would like to work on this too. What would be the rules to validate the yaml file ?

**Comment by muskankhedia** [comment]
@JayjeetAtGithub Thank you for your interest in the project. There are various ways to check the YAML file. One of them is, Initially, you need to check the pattern followed as it should be same as the present one and all the fields are mandatory, so there should be a specific and valid value for every key in the file. And from this, it can be confirmed that the YAML file is valid, ready for parsing and loaded in the server.

**Comment by JayjeetAtGithub** [comment]
@muskankhedia That makes sense. Thanks. I will try to send a PR on this.

**Comment by JayjeetAtGithub** [comment]
@muskankhedia Are we required to show all the errors in the config file and then fail or we can simply fail on encountering the first error ? Like showing one error at a time.

**Comment by Harkishen-Singh** [comment]
I think, we have this now. Closing.
