### ISSUE TITLE
Make bench-routes forced to undergo Safe exit when Ctrl+C

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#46]
This is important. During the execution of modules involving thousands of goroutines, if the application is forced closed via `Ctrl+C`, there are high chances of corrupted data records that could gather or go un-committed in the TSDB. 

We need a mechanism to make all those unsafe methods undergo a definite procedure whenever a `Ctrl+C` or `SIGINT` signal is triggered.

Reference [link](https://stackoverflow.com/a/11269077)

**Comment by ganeshpatro321** [comment]
Will take up this.

**Comment by ganeshpatro321** [comment]
Is this solved @Harkishen-Singh

**Comment by Harkishen-Singh** [comment]
No. This is still to be covered.

**Comment by ganeshpatro321** [comment]
@Harkishen-Singh I was thinking of checking the service state of all the modules from the config file, see whether the state of the modules are active or passive, if active then stop the service, and then os.exit(1) the app. What do you think about this approach?

**Comment by Harkishen-Singh** [comment]
Yes, moreover, explicitly declaring os.exit(0) should be the answer. Putting 1 will show a failure or error.

**Comment by ganeshpatro321** [comment]
Okay, noted.

**Comment by Harkishen-Singh** [comment]
I think we have a level of this currently. Closing this. We can later re-open when this becomes a priority, probably when we handle a million go-routines.
