### ISSUE TITLE
Place config in the root folder

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/bench-routes#49]
#### Describe

Place the `local-config.yml` in the project root and change the respective paths, in order to allow all folders to have access to it.

**Comment by wale-bant** [comment]
Hi, can I work on this?

**Comment by muskankhedia** [comment]
Sure!

**Comment by wale-bant** [comment]
I'm on it.

**Comment by wale-bant** [comment]
Hi, please review my PR #55 and merge. Thanks

**Comment by Harkishen-Singh** [comment]
Solved! Closing it.
