### ISSUE TITLE
Create global var file in utils/

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#51]
currently, the global variables are present in a distributed manner,  i.e., some are present in `tsdb.go`, some at `handlers.go`, `init.go` etc. We need to bring them all in one place in order to make life easier for contributors.

Please note that this file should be named as `global-vars.go` and should be inside the `utils/` directory so that it can be accessed without any `cyclic-import` errors.

**Comment by ganeshpatro321** [comment]
Will look into this. @Harkishen-Singh

**Comment by ganeshpatro321** [comment]
Just to verify, do we need vars such as `GlobalPingChain` in the utils directory. If yes, then  I am facing a cyclic import problem. @Harkishen-Singh , as I will have to import the tsdb folder to utils (to access the parser), and utils to tsdb to access the global vars ?

**Comment by Harkishen-Singh** [comment]
@ganeshpatro321  to avoid it, just declare `GlobalPingChain` only in the utils directory and use it in other packages as `utils.GlobalPingChain`. That should solve the issue.

**Comment by ganeshpatro321** [comment]
Without importing utils there? @Harkishen-Singh
