### ISSUE TITLE
Displaying the log message if the server gets disconnected

### ISSUE THREAD

**Issue by muskankhedia** [zairza-cetb/bench-routes#54]
OS: Fedora

#### Describe
There are chances where the network may get disconnected in the mid of the execution of a function. So displaying the log message when the network gets disconnected will aware the user to reconnect the network and the log will be maintained.

**Comment by Pratik32** [comment]
hello @muskankhedia I would like to work on this one. Is there anyone already working on it ?

**Comment by muskankhedia** [comment]
@Pratik32 Thanks for showing your interest in the project. Currently, this issue is open for contributors. You can work on it and feel free to ask any queries.

**Comment by Pratik32** [comment]
Hello, In order to implement this I was thinking of following:
1) the linux's ping utility return 'could not find host < host_name>' if it cannot connect to the given host.(possibly because of no network connection or something wrong with host itself). If ping returns this message we can log the message.(to make user aware of it).
OR
2) In order to check network connectivity we can ping google's DNS : 8.8.8.8.

**Comment by Pratik32** [comment]
Okay, I just realized that there already a method VerifyConnection() in source code to check external network connectivity, I think we can use it too ?

**Comment by muskankhedia** [comment]
> Hello, In order to implement this I was thinking of following:
> 
> 1. the linux's ping utility return 'could not find host < host_name>' if it cannot connect to the given host.(possibly because of no network connection or something wrong with host itself). If ping returns this message we can log the message.(to make user aware of it).
 
Yaa something similar needs to be done as we need to check if the network gets disconnected in the mid of any operation. A condition should be made to check internet connectivity at every instant and aware the user as soon as the network is disconnected.

**Comment by muskankhedia** [comment]
> Okay, I just realized that there already a method VerifyConnection() in source code to check external network connectivity, I think we can use it too ?

VerifyConnection() checks for internet connectivity only once when the server is started. Now we need to implement an all-time internet connectivity check and warn the user as soon as the network gets disconnected at any instant when the server is running.

**Comment by Pratik32** [comment]
@muskankhedia thanks muskan, I have thought of some code change regarding this. will raise a PR once done.
