### ISSUE TITLE
add Jitter module

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#6]
As per the docs, we require support for Jitter check. Testing jitter on any route is a resource-intensive as various network modules are required and their implementation by the `ping` command happens serially. This could take significant time and hence needs to be implemented as an **independent goroutine**. The communication must be carried out between the threads via pointer/non-pointer channels (depends on the contributors, pointer channel recommended) since the data received is not expected to be huge.

OS: universal

**Comment by aquibbaig** [comment]
I'm taking this!
