### ISSUE TITLE
Consider using Go modules

### ISSUE THREAD

**Issue by agathver** [zairza-cetb/bench-routes#64]
Go 1.12 and up contain a nifty feature called go module system which works very similar to how npm performs.

https://blog.golang.org/using-go-modules

This also allows me to pin to versions and prevent pollution and collision with Go packages already in GOPATH; as explained here - I have a project X which depends on Y @ 1.0.0 and this project also depends on Y @ 2.0.0. The current layout doesn't allow them to coexist and hence collision happens. Go modules is one of the way to solve it.

Note: Go modules will require you to update to Go 1.12

**Comment by Harkishen-Singh** [comment]
Sure @agathver. We were busy in setting up the base and missed this. Thanks for pointing out. Will surely do in the following commits!
