### ISSUE TITLE
If hostname for a particular route is not correct, entire application crashes.

### ISSUE THREAD

**Issue by Pratik32** [zairza-cetb/bench-routes#65]
**Describe the bug**
If we specify wrong hostname in the config file, the application panic while pinging the incorrect hostname.

**To Reproduce**
Steps to reproduce the behaviour:
1.Replace anyone of the hostname in config file with garbage value.
   e.g I replaced www.google.com to www.gougle.com
2.Test the application with socket-tester
3. In the logs it is evident that, when it tries to ping the incorrect hostname error caught and panic() is called for the given routine.  

**Expected behaviour**
1. Since this is happening for a particular hostname, It should continue monitoring other routes/hostnames (which are correct). 
2. If we call panic in this scenario, it panics the entire application.
3. Expected behavior : For the erroneous hostname, a log message should be printed, and nothing should be added to tsdb.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version : master

**Comment by Harkishen-Singh** [comment]
Thanks for pointing out. We are in the early stages for the development. Would be having similar bugs in other modules. 
Thanks for your interest in the project. Expecting more participation!

**Comment by muskankhedia** [comment]
@Pratik32 Thanks for your interest in the project. On examining the cases, I came to know that on invalid URLs the server doesn't panic instead its redirecting to the IP `154.92.19.168` and the complete process works as expected. So there won't be any requirement of any extra conditions foor Invalid URLs.

Screenshot of the redirection of URL in an invalid input:
![WhatsApp Image 2019-10-09 at 7 09 42 PM](https://user-images.githubusercontent.com/36980003/66506114-5624a600-eaea-11e9-84c7-4edf12818913.jpeg)

P.S. The redirecting behaviour is not observed in all the systems, I will surely figure out the reason soon for the same.

**Comment by ankitjena** [comment]
@muskankhedia that doesn't happen in my system
```
ping: www.gougle.com: Name or service not known

```

**Comment by muskankhedia** [comment]
> @muskankhedia that doesn't happen in my system
> 
> ```
> ping: www.gougle.com: Name or service not known
> ```

@ankitjena Yaa same happening in my system, but working fine with Harkishen. So we need to find the basic reason for redirection to the default URL in some of the system.

**Comment by Pratik32** [comment]
Hi @muskankhedia , thanks. did you try the repro steps that I mentioned in the bug report. Can you check the result with those steps.
P.S. I am running this on UBUNTU 18.04. (Although it should not make any difference. as 'ping' utility is same on all linux platforms)

**Comment by muskankhedia** [comment]
@Pratik32 Yaa I have also tried the steps mentioned and the TSDB files are created as expected and everything is working fine after getting redirected to the default URL. But it's working only with some of the system. Now we can solve it in 2 ways:
1. Stopping the redirection to the default URL in the system (this can be done by initially checking the URLs, either it is valid or not).
2. As mentioned by you earlier, sending the null string as the response for the invalid URLs (but redirecting needs to be stopped before that else this method may work only for some of the systems).

For the timing, I can think of these solutions. Other ideas are also most welcome.

**Comment by Pratik32** [comment]
@muskankhedia , I think 154.92.19.168 is ip of your router OR service endpoint. I still can't explain the behaviour of the ping command though. Anyways I think there must be some error handing in case ping returns actual error.

**Comment by muskankhedia** [comment]
@Pratik32 I get your point and facing the same error in my system but its working fine with some of the other systems. So need to first figure out the actual problem before solving it.

**Comment by Harkishen-Singh** [comment]
> @muskankhedia that doesn't happen in my system
> 
> ```
> ping: www.gougle.com: Name or service not known
> ```

@ankitjena @muskankhedia  ping will never work with `www`. As discussed before, it has to be a pure domain or pure IP, the hyperlinks are never supported in `ping CLI`. Similarly, `ping www.google.co.in` will never work, but remove the `www`, then it will work!

**Comment by Harkishen-Singh** [comment]
@Pratik32 could you please confirm whether running `ping -c 10 guogle.co.in` in simple terminal is causing issues?

**Comment by Pratik32** [comment]
@Harkishen-Singh , here is the output of above command on my machine.
![ss](https://user-images.githubusercontent.com/17097242/66516838-993d4400-eaff-11e9-81a6-f9ac4b580eea.PNG)

**Comment by Harkishen-Singh** [comment]
I think this is fixed now. Feel free to reopen if not.
