### ISSUE TITLE
scheduled benchmarking

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#77]
features like monitoring will run always in the background. However, the benchmark test could not be run forever (depends on the user) since they would add to the cost of the VM instance and are cost-intensive.

This leads to an approach to a scheduled scheme of benchmarking which would be as an optional feature.

**Comment by aquibbaig** [comment]
@Harkishen-Singh Depends on #113. We can schedule it to run at specific interval.

**Comment by Harkishen-Singh** [comment]
Yes. However, this needs to be done from within the go scripts I suppose. What do you think?
