### ISSUE TITLE
support for flood ping test

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#8]
Desktop (please complete the following information): universal

OS:  fedora
#### Describe

Currently, the ping modules support basic ping functionality. However, functions like flood ping, which is critical for getting the packets loss via propagating through the network. 

Deliverables:

1. data packet loss
2. support via sudo/without sudo operations

**Comment by ankitjena** [comment]
So executing the flood ping command requires sudo in most of the cases(for results that we need actually). A workflow would be to ask the user for his/her password the first time and store it somewhere. And we can input this directly when the command asks for password. If the password is wrong we can reask the user for password.

> This will be done in the GUI

WDYT about this?

I haven't searched much, but @Harkishen-Singh do you know how to pass in a text to the sudo process
```
[sudo] password for ankitj: 

```

**Comment by muskankhedia** [comment]
@ankitjena In order to pass the password in the execution command, the following syntax could be used:

`echo -e "<password>\n" | sudo -S <sudo command to be executed>`

For example, the command to update the system will be:
If the password is 'abcd'

`echo -e "abcd\n" | sudo -S apt-get update -y`

**Comment by Harkishen-Singh** [comment]
closing this!
