### ISSUE TITLE
support for monitoring routes at regular intervals

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#9]
OS: universal

#### Describe

Monitoring is a very critical component of BR. Hence, this will require a very systematic approach to its solution. A brief idea of what I think would be, setting up configuration via `.yml `file for asking routes, intervals of pings, etc. On a latter stage, this will require integration with tsdb.

**Comment by aquibbaig** [comment]
I'd like to take this up
