### ISSUE TITLE
Make tsdb save() call only when required

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#96]
Bench-routes have been designed to handle monitoring and benchmarking on thousands of routes simultaneously by launching independent light-weight goroutines. This means that the storage needs to be robust and capable of handling such large data which it is. This indirectly means that the design of tsdb is goroutine safe.

But here comes the problem.

We are committing into the secondary storage after each iteration. Making the iterations on thousands of routes, the committing is increases even more. This is all without even considering the scaling of tests. Hence, since each iteration writes in the end, the HDD head has to move to and fro several lakhs of times, making the writing process incredibly painful.

One thing which we can do is to write only after a certain limit has reached. This could lessen the pain considerably.

Important Points:
1. The `save / commit` interval must be taken as input, like config file
2. Should be goroutine safe
3. Corresponding tests should be written as well

**Comment by aquibbaig** [comment]
I'd work on this

**Comment by aquibbaig** [comment]
Any progress on this yet? @Harkishen-Singh cause I'd pick this up rn.

**Comment by Harkishen-Singh** [comment]
@aquibbaig no progress on this. Feel free to take it up.

As an initial approach, I think we need to have a global flush that flushes the samples into the database based on two approaches:

1. after a certain time
2. after a certain number of samples in the chain.

Also, the flush should be only in those chains which have new changes, not all the chains. And, this flush operation should occur at once itself wherein a single go, all chains have their data flushed. Thas the only main thing that needs to be kept in mind. Args based channels (not strictly) should be best to use here.

**Comment by Harkishen-Singh** [comment]
This is fixed in #233. Closing this.
