### ISSUE TITLE
Initialise all service states to passive on start

### ISSUE THREAD

**Issue by Harkishen-Singh** [zairza-cetb/bench-routes#97]
When the BR application starts, it has all its module states in a halt mode. But the local-config.yml _(which is also a local db)_ does not say so. This creates a mismatch as when the application is forced close (due to various reasons), the service state remains in its original state even after being crashed. This prevents the services from being started _(unless stopped manually from the UI end)_. We need to re-initialise the `service-states` in local-config.yml to **passive** when the BR starts.

**Comment by Pratik32** [comment]
I am working on this one.

**Comment by Harkishen-Singh** [comment]
Sure @Pratik32.

You can also participate in the development of GUI for benchroutes. [Link](https://www.github.com/zairza-cetb/bench-routes-electron)

**Comment by Harkishen-Singh** [comment]
@Pratik32 any updates?

**Comment by Pratik32** [comment]
@Harkishen-Singh , I did not get time this week for it. I will work on it during weekend.

**Comment by Pratik32** [comment]
@Harkishen-Singh , I did not get time this week for it. I will work on it during weekend.
